baseURL = "https://princexraj.github.io/"
languageCode = "en-us"
title = "Prince Raj"
theme = "PaperMod"

[params]
  env = "production"
  description = "Founder of avnilabs.ai - Building AI Products"
  author = "Prince Raj"

  # Favicon
  favicon = "/favicon.ico"

  # Theme settings
  defaultTheme = "auto" # auto, light, dark
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/princeraj"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/princexraj"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/prince__seeker"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:prince@princeraj.dev"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
